package entity;
// Generated Apr 28, 2018 6:01:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipos generated by hbm2java
 */
public class Equipos  implements java.io.Serializable {


     private int idEquipos;
     private String ip;
     private String nombre;
     private Integer intervalo;
     private Set tiempoequiposesForIdEquipo = new HashSet(0);
     private Set tiempoequiposesForIdEquipoNext = new HashSet(0);

    public Equipos() {
    }

	
    public Equipos(int idEquipos) {
        this.idEquipos = idEquipos;
    }
    public Equipos(int idEquipos, String ip, String nombre, Integer intervalo, Set tiempoequiposesForIdEquipo, Set tiempoequiposesForIdEquipoNext) {
       this.idEquipos = idEquipos;
       this.ip = ip;
       this.nombre = nombre;
       this.intervalo = intervalo;
       this.tiempoequiposesForIdEquipo = tiempoequiposesForIdEquipo;
       this.tiempoequiposesForIdEquipoNext = tiempoequiposesForIdEquipoNext;
    }
    public Equipos (String ip, String nombre, Integer intervalo)
    {
       this.ip = ip;
       this.nombre = nombre;
       this.intervalo = intervalo; 
    }
    public int getIdEquipos() {
        return this.idEquipos;
    }
    
    public void setIdEquipos(int idEquipos) {
        this.idEquipos = idEquipos;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getIntervalo() {
        return this.intervalo;
    }
    
    public void setIntervalo(Integer intervalo) {
        this.intervalo = intervalo;
    }
    public Set getTiempoequiposesForIdEquipo() {
        return this.tiempoequiposesForIdEquipo;
    }
    
    public void setTiempoequiposesForIdEquipo(Set tiempoequiposesForIdEquipo) {
        this.tiempoequiposesForIdEquipo = tiempoequiposesForIdEquipo;
    }
    public Set getTiempoequiposesForIdEquipoNext() {
        return this.tiempoequiposesForIdEquipoNext;
    }
    
    public void setTiempoequiposesForIdEquipoNext(Set tiempoequiposesForIdEquipoNext) {
        this.tiempoequiposesForIdEquipoNext = tiempoequiposesForIdEquipoNext;
    }




}


