package entity;
// Generated 2/05/2018 02:24:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipos generated by hbm2java
 */
public class Equipos  implements java.io.Serializable {


     private int idEquipos;
     private String ip;
     private String nombre;
     private Integer intervalo;
     private Set tiempoEquiposesForIdEquipo = new HashSet(0);
     private Set tiempoEquiposesForIdEquipoNext = new HashSet(0);

    public Equipos() {
    }

	
    public Equipos(int idEquipos) {
        this.idEquipos = idEquipos;
    }
    public Equipos(int idEquipos, String ip, String nombre, Integer intervalo, Set tiempoEquiposesForIdEquipo, Set tiempoEquiposesForIdEquipoNext) {
       this.idEquipos = idEquipos;
       this.ip = ip;
       this.nombre = nombre;
       this.intervalo = intervalo;
       this.tiempoEquiposesForIdEquipo = tiempoEquiposesForIdEquipo;
       this.tiempoEquiposesForIdEquipoNext = tiempoEquiposesForIdEquipoNext;
    }
   
    public int getIdEquipos() {
        return this.idEquipos;
    }
    
    public void setIdEquipos(int idEquipos) {
        this.idEquipos = idEquipos;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getIntervalo() {
        return this.intervalo;
    }
    
    public void setIntervalo(Integer intervalo) {
        this.intervalo = intervalo;
    }
    public Set getTiempoEquiposesForIdEquipo() {
        return this.tiempoEquiposesForIdEquipo;
    }
    
    public void setTiempoEquiposesForIdEquipo(Set tiempoEquiposesForIdEquipo) {
        this.tiempoEquiposesForIdEquipo = tiempoEquiposesForIdEquipo;
    }
    public Set getTiempoEquiposesForIdEquipoNext() {
        return this.tiempoEquiposesForIdEquipoNext;
    }
    
    public void setTiempoEquiposesForIdEquipoNext(Set tiempoEquiposesForIdEquipoNext) {
        this.tiempoEquiposesForIdEquipoNext = tiempoEquiposesForIdEquipoNext;
    }




}


