package entity;
// Generated 2/05/2018 02:24:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LamportCentral generated by hbm2java
 */
public class LamportCentral  implements java.io.Serializable {


     private int idCentral;
     private Integer contNuevo;
     private Integer contLocal;
     private Set tiempoEquiposes = new HashSet(0);

    public LamportCentral() {
    }

	
    public LamportCentral(int idCentral) {
        this.idCentral = idCentral;
    }
    public LamportCentral(int idCentral, Integer contNuevo, Integer contLocal, Set tiempoEquiposes) {
       this.idCentral = idCentral;
       this.contNuevo = contNuevo;
       this.contLocal = contLocal;
       this.tiempoEquiposes = tiempoEquiposes;
    }
   
    public int getIdCentral() {
        return this.idCentral;
    }
    
    public void setIdCentral(int idCentral) {
        this.idCentral = idCentral;
    }
    public Integer getContNuevo() {
        return this.contNuevo;
    }
    
    public void setContNuevo(Integer contNuevo) {
        this.contNuevo = contNuevo;
    }
    public Integer getContLocal() {
        return this.contLocal;
    }
    
    public void setContLocal(Integer contLocal) {
        this.contLocal = contLocal;
    }
    public Set getTiempoEquiposes() {
        return this.tiempoEquiposes;
    }
    
    public void setTiempoEquiposes(Set tiempoEquiposes) {
        this.tiempoEquiposes = tiempoEquiposes;
    }




}


