package entity;
// Generated Apr 28, 2018 6:01:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lamportcentral generated by hbm2java
 */
public class Lamportcentral  implements java.io.Serializable {


     private int idCentral;
     private Integer contNuevo;
     private Integer contLocal;
     private Set tiempoequiposes = new HashSet(0);

    public Lamportcentral() {
    }

	
    public Lamportcentral(int idCentral) {
        this.idCentral = idCentral;
    }
    public Lamportcentral(int idCentral, Integer contNuevo, Integer contLocal, Set tiempoequiposes) {
       this.idCentral = idCentral;
       this.contNuevo = contNuevo;
       this.contLocal = contLocal;
       this.tiempoequiposes = tiempoequiposes;
    }
   
    public int getIdCentral() {
        return this.idCentral;
    }
    
    public void setIdCentral(int idCentral) {
        this.idCentral = idCentral;
    }
    public Integer getContNuevo() {
        return this.contNuevo;
    }
    
    public void setContNuevo(Integer contNuevo) {
        this.contNuevo = contNuevo;
    }
    public Integer getContLocal() {
        return this.contLocal;
    }
    
    public void setContLocal(Integer contLocal) {
        this.contLocal = contLocal;
    }
    public Set getTiempoequiposes() {
        return this.tiempoequiposes;
    }
    
    public void setTiempoequiposes(Set tiempoequiposes) {
        this.tiempoequiposes = tiempoequiposes;
    }




}


