package entity;
// Generated 2/05/2018 02:24:42 PM by Hibernate Tools 4.3.1



/**
 * TiempoEquipos generated by hbm2java
 */
public class TiempoEquipos  implements java.io.Serializable {


     private int idTiempoEq;
     private Equipos equiposByIdEquipo;
     private Equipos equiposByIdEquipoNext;
     private LamportCentral lamportCentral;
     private String cequipo;
     private String cmensaje;

    public TiempoEquipos() {
    }

	
    public TiempoEquipos(int idTiempoEq) {
        this.idTiempoEq = idTiempoEq;
    }
    public TiempoEquipos(int idTiempoEq, Equipos equiposByIdEquipo, Equipos equiposByIdEquipoNext, LamportCentral lamportCentral, String cequipo, String cmensaje) {
       this.idTiempoEq = idTiempoEq;
       this.equiposByIdEquipo = equiposByIdEquipo;
       this.equiposByIdEquipoNext = equiposByIdEquipoNext;
       this.lamportCentral = lamportCentral;
       this.cequipo = cequipo;
       this.cmensaje = cmensaje;
    }
    
    public TiempoEquipos(Equipos equiposByIdEquipo, Equipos equiposByIdEquipoNext, LamportCentral lamportCentral, String cequipo, String cmensaje) {
       this.idTiempoEq = idTiempoEq;
       this.equiposByIdEquipo = equiposByIdEquipo;
       this.equiposByIdEquipoNext = equiposByIdEquipoNext;
       this.lamportCentral = lamportCentral;
       this.cequipo = cequipo;
       this.cmensaje = cmensaje;
    }
   
    public int getIdTiempoEq() {
        return this.idTiempoEq;
    }
    
    public void setIdTiempoEq(int idTiempoEq) {
        this.idTiempoEq = idTiempoEq;
    }
    public Equipos getEquiposByIdEquipo() {
        return this.equiposByIdEquipo;
    }
    
    public void setEquiposByIdEquipo(Equipos equiposByIdEquipo) {
        this.equiposByIdEquipo = equiposByIdEquipo;
    }
    public Equipos getEquiposByIdEquipoNext() {
        return this.equiposByIdEquipoNext;
    }
    
    public void setEquiposByIdEquipoNext(Equipos equiposByIdEquipoNext) {
        this.equiposByIdEquipoNext = equiposByIdEquipoNext;
    }
    public LamportCentral getLamportCentral() {
        return this.lamportCentral;
    }
    
    public void setLamportCentral(LamportCentral lamportCentral) {
        this.lamportCentral = lamportCentral;
    }
    public String getCequipo() {
        return this.cequipo;
    }
    
    public void setCequipo(String cequipo) {
        this.cequipo = cequipo;
    }
    public String getCmensaje() {
        return this.cmensaje;
    }
    
    public void setCmensaje(String cmensaje) {
        this.cmensaje = cmensaje;
    }




}


